---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: centos-6.5
  - name: rhel-6.5

suites:
  - name: default
    run_list:
      - recipe[fs-create::default]
    attributes:
      appsvc:
        service:
          users: "root","nobody"
